version: "3.1"
services:
  db:
    container_name: pdb
    image: postgres:14.3-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DMP_RT_DB_NAME}

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8080:8080"