[tool.poetry]
name = "UrFU_data_science_project"
version = "0.0.1"
description = "UrFU educational project"
authors = [
    "Vladimir Katin <katin.v.v.@gmail.com>",
    "Anna Bezhenar <asbezhenar@gmail.com>",
    "Anton Bessolitsyn <Anton.Bessolitsyn@hotmail.com>"
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/urfuMagDS2022SFgroup/sf_data_science_python"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
transformers = "^4.24.0"
numpy = "^1.23.2"

[tool.poetry.group.torch]
optional = true

[tool.poetry.group.tensorflow]
optional = true

[tool.poetry.group.torch.dependencies]
torch = "1.13.0"
torchvision = "0.14.0"
torchaudio = "0.13.0"

[tool.poetry.group.tensorflow.dependencies]
tensorflow-cpu = "2.10.0"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
