[tool.poetry]
name = "UrFU_data_science_project"
version = "0.0.1"
description = "UrFU educational project"
authors = [
    "Vladimir Katin <katin.v.v.@gmail.com>",
    "Anna Bezhenar <asbezhenar@gmail.com>",
    "Anton Bessolitsyn <Anton.Bessolitsyn@hotmail.com>"
]
license = "GNU"
readme = "README.md"

[tool.poetry.group.linux_torch]
optional = true

[tool.poetry.group.windows_torch]
optional = true

[tool.poetry.group.mac_torch]
optional = true

[tool.poetry.group.tensorflow]
optional = true

[tool.poetry.dependencies]
python = "^3.10"
transformers = "^4.24.0"
numpy = "^1.23.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.linux_torch.dependencies]
torch = { url = "https://download.pytorch.org/whl/cpu/torch-1.13.0%2Bcpu-cp310-cp310-linux_x86_64.whl" }
torchaudio = { url = "https://download.pytorch.org/whl/cpu/torchaudio-0.13.0%2Bcpu-cp310-cp310-linux_x86_64.whl" }
torchvision = { url = "https://download.pytorch.org/whl/cpu/torchvision-0.14.0%2Bcpu-cp310-cp310-linux_x86_64.whl" }


[tool.poetry.group.windows_torch.dependencies]
torch = { url = "https://download.pytorch.org/whl/cpu/torch-1.13.0%2Bcpu-cp310-cp310-win_amd64.whl" }
torchaudio = { url = "https://download.pytorch.org/whl/cpu/torchaudio-0.13.0%2Bcpu-cp310-cp310-win_amd64.whl" }
torchvision = { url = "https://download.pytorch.org/whl/cpu/torchvision-0.14.0%2Bcpu-cp310-cp310-win_amd64.whl" }

[tool.poetry.group.mac_torch.dependencies]
torch = "^1.13.0"
torchaudio = "^0.13.0"
torchvision = "^0.14.0"

[tool.poetry.group.tensorflow.dependencies]
tensorflow-cpu = "2.10.0"
