[tool.poetry]
name = "UrFU_data_science_project"
version = "0.0.1"
description = "UrFU educational project"
authors = [
    "Vladimir Katin <katin.v.v.@gmail.com>",
    "Anna Bezhenar <asbezhenar@gmail.com>",
    "Anton Bessolitsyn <Anton.Bessolitsyn@hotmail.com>"
]
license = "GNU"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
transformers = "^4.24.0"
numpy = "^1.23.2"
torch = { version = "1.9.1", source = "torch" }
torchaudio = { version = "0.13.0", source = "torch" }
torchvision = { version = "0.14.0", source = "torch" }
torchtext = { version = "0.14.0", source = "torch" }

[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cpu"
secondary = true


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
